name: Flutter test CI

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:

    runs-on: macos-latest

    steps:
      - uses: actions/checkout@v2
      - uses: subosito/flutter-action@v1.3.0
        with:
          flutter-version: '1.12.13+hotfix.9'
      - run: flutter pub get
      - run: flutter test
